Keeper
skip-mev/osmosis-protorev pull request #17
Opened 2022-11-16 21:54 UTC by davidterpay

2022-11-17 04:43 UTC, NotJeremyLiu requested changes
Fire sir. I left comments (some my own, some from github actions - idk if this a good method or if u already notified of em / no need for me to screenshot)

2022-11-17 04:43 UTC, NotJeremyLiu commented on proto/osmosis/protorev/v1beta1/params.proto
> +  bool only_check_hot_routes = 1;
I think this should be just named: check_hot_routes 

- I think there's a good chance the algo first checks the highest liquidity route, and then hot routes (if available). So it'll never be only hot routes, but highest liquidity first and then hot routes (if that pool has em)

2022-11-17 04:43 UTC, NotJeremyLiu commented on x/protorev/keeper/protorev.go
> +	store := prefix.NewStore(ctx.KVStore(k.storeKey), []byte(types.KeyPrefixOsmoPools))
types.KeyPrefixOsmoPools already of type []byte, so no need for the conversion

2022-11-17 04:43 UTC, NotJeremyLiu commented on x/protorev/keeper/protorev.go
> +	store := prefix.NewStore(ctx.KVStore(k.storeKey), []byte(types.KeyPrefixAtomPools))
types.KeyPrefixAtomPools is already of type []byte, no need for the conversion

2022-11-17 04:43 UTC, NotJeremyLiu commented on x/protorev/keeper/protorev.go
> +	key := types.GetKeyPrefixRouteForPoolID(poolID)
If we're using poolID as the key, I think we should just pass this variable around and not store poolId within the SearcherRoute keeper.

2022-11-17 04:43 UTC, NotJeremyLiu commented on proto/osmosis/protorev/v1beta1/protorev.proto
> +  uint64 pool_id = 3 [(gogoproto.nullable) = false];
Connected with other comment, if they key is pool_id I don't think we should also store it

2022-11-17 04:43 UTC, NotJeremyLiu commented on x/protorev/keeper/protorev.go
> +	return searchRoutes, nil
![Screen Shot 2022-11-16 at 9 32 49 PM](https://user-images.githubusercontent.com/31809888/202355980-cfd8b170-ca4a-48f0-a9e6-39d840ac5533.png)

2022-11-17 04:43 UTC, NotJeremyLiu commented on x/protorev/keeper/protorev.go
> +	store := prefix.NewStore(ctx.KVStore(k.storeKey), []byte(types.KeyPrefixRoutes))
![Screen Shot 2022-11-16 at 9 33 15 PM](https://user-images.githubusercontent.com/31809888/202356041-dcd2a620-f0c1-487f-bfc6-95e8b9a7da4a.png)

2022-11-17 04:43 UTC, NotJeremyLiu commented on x/protorev/keeper/protorev.go
> +	store := prefix.NewStore(ctx.KVStore(k.storeKey), []byte(types.KeyPrefixProtoRevStatistics))
![Screen Shot 2022-11-16 at 9 33 33 PM](https://user-images.githubusercontent.com/31809888/202356078-c03ca8d5-696c-4c3d-8f26-01c6ce23ac83.png)

2022-11-17 04:43 UTC, NotJeremyLiu commented on x/protorev/keeper/protorev.go
> +	protoRevStatistics.Unmarshal(bz)
![Screen Shot 2022-11-16 at 9 33 54 PM](https://user-images.githubusercontent.com/31809888/202356121-1a3f96ff-c28c-473c-8d3a-4c746fca688f.png)

2022-11-17 04:43 UTC, NotJeremyLiu commented on x/protorev/keeper/protorev.go
> +	store := prefix.NewStore(ctx.KVStore(k.storeKey), []byte(types.KeyPrefixProtoRevStatistics))
![Screen Shot 2022-11-16 at 9 34 29 PM](https://user-images.githubusercontent.com/31809888/202356173-19d3578d-91dc-4e81-a811-94cfe0718ed7.png)

2022-11-17 04:43 UTC, NotJeremyLiu commented on x/protorev/types/genesis.go
> +var OsmosisDenomination string = "OSMO"
If we're going to use these to check denoms against, then we will need to switch osmo to "uosmo" and atom to "ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2"

2022-11-17 04:43 UTC, NotJeremyLiu commented on x/protorev/types/utils.go
> +	return uint64(binary.LittleEndian.Uint64(bz))
![Screen Shot 2022-11-16 at 9 40 46 PM](https://user-images.githubusercontent.com/31809888/202357150-d8c68a55-d6e0-424c-bc1f-5bb42ff334c8.png)

2022-11-17 16:00 UTC, davidterpay commented on proto/osmosis/protorev/v1beta1/params.proto
> +  bool only_check_hot_routes = 1;
i agree i think that makes the most sense

2022-11-17 19:41 UTC, nivasan1 requested changes
@davidterpay looks clean, thorough tests, I made a few small comments. One thing to address though is that I don't think the storage schema for storing protoRevStatistics makes sense, We should instead just make separate storage keys for each of the member fields so that lookups /sets are faster, and we don't have to write storage migrations if we intend to change what statistics we are using in the future.

2022-11-17 19:41 UTC, nivasan1 commented on proto/osmosis/protorev/v1beta1/genesis.proto
> +  repeated SearcherRoutes routes = 2 [ (gogoproto.nullable) = false ];
Also why is routes nullable here but not in  SearcherRoutes?

2022-11-17 19:41 UTC, nivasan1 commented on proto/osmosis/protorev/v1beta1/protorev.proto
> +  map<string, uint64> profits = 2;
Why are profits / pools map objects stored in state as part of the ProtoRevStatistics obj. would it make sense to store them in KVStore, and index via poolID or token denom?

2022-11-17 19:41 UTC, nivasan1 commented on proto/osmosis/protorev/v1beta1/tx.proto
> +service Msg {}
nit: Does this need to be here? If there is not MsgHandler / tx Message types?

2022-11-17 19:41 UTC, nivasan1 commented on proto/osmosis/protorev/v1beta1/protorev.proto
> +  repeated Route routes = 1;
this will be represented as a slice of pointers I don't think this makes sense. Using pointers in sdk unless necessary introduces large runtime overhead for garbage collection of the pointer / possible non-determinism if the pointers are persisted to state somewhere.

2022-11-17 19:41 UTC, nivasan1 commented on x/protorev/keeper/protorev.go
> +func (k Keeper) SetProtoRevStatistics(ctx sdk.Context, protoRevStatistics *types.ProtoRevStatistics) {
@davidterpay See comment regarding protoRevStatistics in proto, I don't think this storage schema makes sense, makes more sense to use PoolDenoms / PoolIDs to uniquely determine keys, and store unit64s in state instead of the entire protoRevStatistics obj.

2022-11-17 19:41 UTC, nivasan1 commented on x/protorev/types/genesis.go
> +		tokenPair := TokenPair{
Why not just concatenate TokenA + TokenB and use that as index in map to determine uniqueness, seems weird to use struct as index into map for determining uniqueness of obj?

2022-11-17 20:42 UTC, davidterpay commented on proto/osmosis/protorev/v1beta1/protorev.proto
> +  map<string, uint64> profits = 2;
Ill make a linear task for this because i dont want this to be a blocker for now but i completely agree.

2022-11-17 20:45 UTC, davidterpay commented on proto/osmosis/protorev/v1beta1/tx.proto
> +service Msg {}
We might implement it later, ill add a linear task where me and jeremy can determine if it makes sense to completely remove.

2022-11-17 20:48 UTC, davidterpay commented on x/protorev/types/genesis.go
> +		tokenPair := TokenPair{
achieves the same end goal but i think this is a little bit more readable

2022-11-18 20:08 UTC, MaghnusM commented on x/protorev/module.go
> +		panic(err)
have you thought deeply about panicking this

2022-11-18 20:08 UTC, MaghnusM commented on x/protorev/genesis.go
> +		panic(err)
think deeply about this

2022-11-18 20:13 UTC, MaghnusM commented on x/protorev/types/searcher_routes.go
> +			return sdkerrors.Wrapf(ErrInvalidRoute, "the length of the entered cyclic arbitrage route must hit at least three pools: entered number of pools %d", len(uniquePools))
"exactly three pools"

2022-11-18 20:17 UTC, MaghnusM commented on proto/osmosis/protorev/v1beta1/protorev.proto
> +  // The number of artbitrages that have been executed by the module account
nit - mispelled

2022-11-18 20:22 UTC, davidterpay commented on x/protorev/types/searcher_routes.go
> +			return sdkerrors.Wrapf(ErrInvalidRoute, "the length of the entered cyclic arbitrage route must hit at least three pools: entered number of pools %d", len(uniquePools))
fixed in the follow up PR

2022-11-18 20:39 UTC, bpiv400 requested changes
### High Level
This is great, especially appreciate the careful work around validating inputs. Some comments below, mostly around naming and data structure choices. 

@notjeremyliu for visibility

### Comments
1. We should borrow naming conventions and data structure conventions from GAMM whenever possible. The Osmosis core team is going to need to get comfortable with this code, and we want to make it as easy as possible for them to understand it. 
2. "Searcher" is a strange name in "SearcherRoutes". We should call this something that indicates its the routes for a particular pool. It's also odd that the SearcherRoutes object takes a Searcher field.  
3. 

### Questions
1. Does it make more sense to have a tokenA and tokenB field than a Denoms slice / array? 
2. Is there any way we can do more intelligent checking for denoms that are valid or invalid? (e.g. checking against some list of denoms that exist in pools that we can pull out of GAMM?) 
4. Are the "searcher routes" objects routes for particular pools or particular token pairs, designed to be used across a variety of pools that may have those token pairs?

2022-11-18 20:39 UTC, bpiv400 commented on x/protorev/types/genesis.go
> +			TokenA: searcherRoutes.TokenA,
Check naming norms in GAMM to ensure we're calling familiar concepts by familiar names

2022-11-18 20:39 UTC, bpiv400 commented on x/protorev/types/genesis.go
> +		if tokenPair.TokenA > tokenPair.TokenB {
Comment for clarification on alphabetization

2022-11-18 20:39 UTC, bpiv400 commented on x/protorev/types/genesis.go
> +	for _, searcherRoutes := range gs.Routes {
Let's call these arbRoutes?

2022-11-18 20:39 UTC, bpiv400 commented on proto/osmosis/protorev/v1beta1/params.proto
> +  // Boolean that determines whether x/protorev will search routes at runtime
Slightly misleading comment?

2022-11-18 21:22 UTC, davidterpay commented
> 1. We should borrow naming conventions and data structure conventions from GAMM whenever possible. The Osmosis core team is going to need to get comfortable with this code, and we want to make it as easy as possible for them to understand it.

Outside of the naming convention we decide to go with for the hot routes, I have been modeling the same convention that the GAMM module uses.

> 2. "Searcher" is a strange name in "SearcherRoutes". We should call this something that indicates its the routes for a particular pool. It's also odd that the SearcherRoutes object takes a Searcher field.


@NotJeremyLiu any idea for what we should name the store? For naming, i'm thinking Each token pair can map to a `Searcher` object that contains a `ArbRoutes` field.

> 1. Does it make more sense to have a tokenA and tokenB field than a Denoms slice / array?


I think it doesn't really matter but its easier to reason about with only tokenA and tokenB since `protorev` will only be looking at pools with two assets. 

 
> 2. Is there any way we can do more intelligent checking for denoms that are valid or invalid? (e.g. checking against some list of denoms that exist in pools that we can pull out of GAMM?)


Most of the validation happening for hot route checking is stateless, meaning we can't access the state to check if the denoms are valid or not. We can check whether a denom exists in the bank.

> 3. Are the "searcher routes" objects routes for particular pools or particular token pairs, designed to be used across a variety of pools that may have those token pairs?

Exactly, the searcher routes are indexed by token pair meant to be used across a variety of pools that have the same pair of assets.

2022-11-18 21:40 UTC, davidterpay commented on x/protorev/types/genesis.go
> +			TokenA: searcherRoutes.TokenA,
Per my reply, we are using the same lingo that the GAMM module uses for the most part. The only thing is the pools might have more than two tokens in them so they use an array/slice of tokens, but for simplicity and readability i think it makes the most sense to keep it this way (since we only interact with pools with two assets).

2022-11-18 21:41 UTC, davidterpay commented on x/protorev/types/genesis.go
> +		if tokenPair.TokenA > tokenPair.TokenB {
used to ensure that only one pair of the same tokens exists in the hot routes (otherwise it might get overwritten by the same pair but in different order).

2022-11-18 21:55 UTC, NotJeremyLiu commented
> > 2. "Searcher" is a strange name in "SearcherRoutes". We should call this something that indicates its the routes for a particular pool. It's also odd that the SearcherRoutes object takes a Searcher field.
> 
> @NotJeremyLiu any idea for what we should name the store? For naming, i'm thinking Each token pair can map to a `Searcher` object that contains a `ArbRoutes` field.
> 

I think calling the store tokenPairArbRoutes would be fine

2022-11-18 22:01 UTC, davidterpay commented
> I think calling the store tokenPairArbRoutes would be fine

I agree I'll make these changes and update the PR.

2022-11-18 22:54 UTC, merged